# Generated by Django 5.0.8 on 2024-09-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
